### ISSUE TITLE
Change the tool tip for Ticket Sending Method setting

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/bkap-printable-tickets#12]
Change the tooltip from "Enable Send 1 ticket per quantity to send ticket for each product and each quantity of product in order and Send 1 ticket per product to send each ticket per product in order." 
to:
" 'Enable Send 1 ticket per quantity' to send a ticket for each product and each quantity of product in an order and 'Send 1 ticket per product' to send each ticket per product in an order. "

**Comment by apeksha10** [comment]
This is a very old issue 

None of the clients has come up with this issue 

Hence I have closed this issue.
