### ISSUE TITLE
Mention Quantity on tickets 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/bkap-printable-tickets#16]
Please mention quantity on tickets which is received via email.

For example: If we go through "Send 1 tickets for one product" wise then how we know quantity about this product"

http://screencast.com/t/WkgdHWeb51N   (Recievd Thanku emails)
http://screencast.com/t/uRNh5Tbv           (Received Tickets ) 

If we go for "Send 1 tickets for one quantity" wise then

http://screencast.com/t/JbP4fTg5Fh   (received thanku emails)
http://screencast.com/t/Yf59zAX50BF  (received Tickets)

**Comment by priyanka-tychesoftwares** [comment]
I am closing this issue as it is a duplicate and added [here ](https://github.com/TycheSoftwares/bkap-printable-tickets/issues/2)
