### ISSUE TITLE
Re-sending the printable ticket once sent

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/bkap-printable-tickets#17]
When already a printable ticket is sent, from Edit Order page, we should be able to send the ticket again to the customer as per the setting in the addon setting and the security code and ticket id.

**Comment by priyanka-tychesoftwares** [comment]
There is no client has asked for this feature yet. But I think this will be a useful feature when the booking details are edited or rescheduled so I am keeping it open now.
