### ISSUE TITLE
The Quantity is not displayed in the ticket email

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/bkap-printable-tickets#2]
When I have setting 1 ticket per product( http://screencast.com/t/qtDS9nFhZ ), the number of quantity is not displayed in the ticket email. I had 3 Chairs booked here-http://screencast.com/t/bq9UwfEfOD but in the ticket there is no mention of the qty booked: http://screencast.com/t/qXWLHAncai

**Comment by priyanka-tychesoftwares** [comment]
Closing this issue as there is no client has asked for this yet.
