### ISSUE TITLE
On woo-order page shows wrong "Book By name" 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/bkap-printable-tickets#26]
Here i placed some issue with the name of Apeksha Desai and the woo-order page shows Priyaka Japat which is wrong but it shows properly on View booking page.

https://www.screencast.com/t/6hCHGaDluDJ
https://www.screencast.com/t/fAgDXMoN2

This issue is not related to our plugin

**Comment by priyanka-tychesoftwares** [comment]
Not able to replicate this issue hence closing it.
