### ISSUE TITLE
Fatal error is come by clicking "Print" Button on View Booking page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/bkap-printable-tickets#27]
Testing with WooCommerce 3.3.1 version
settings on Addon setting page : https://www.screencast.com/t/fD47cvnTRg
Place the order. On View Booking page clicking Print button it shows Fatal error.
https://www.screencast.com/t/WnIdvFsuuhw
CSV button works fine 

This fatal error also comes with an old version of WooCommerce 3.2.6

**Comment by priyanka-tychesoftwares** [comment]
I am unable to replicate this issue with the latest plugin versions hence closing this issue.
