### ISSUE TITLE
1st January 1970 is coming in the ticket instead of the actual booking date 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/bkap-printable-tickets#28]
Screenshot of ticket: https://prnt.sc/oiveom 
Actual date: https://prnt.sc/oivf56 

So, the ticket in the email is not updating the actual date. 

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/9200

**Comment by priyanka-tychesoftwares** [comment]
I am unable to replicate this issue now hence closing this one.
