### ISSUE TITLE
Warnings are displayed when the setting is enabled from Global settings.

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/bkap-printable-tickets#5]
When the addon is active, there are 2 warnings displayed on the Global settings page. http://screencast.com/t/lGRXX90Si3q9 and http://screencast.com/t/Zclxq06Gt. 

And when an order is marked Completed, on saving the order, this warning is displayed: http://screencast.com/t/ahq6Yhq1PaX. 

Also the email received by the customer has this warning displayed: http://screencast.com/t/iN3RjzS21g

**Comment by priyanka-tychesoftwares** [comment]
I am closing this issue as it is too old and I never faced such an issue.
