### ISSUE TITLE
The View booking page is having multiple records

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/bkap-printable-tickets#9]
With printable tickets addon, when an order is placed for a product for 13th Feb for 4 qty and same product for 8th of Feb for 1 qty http://screencast.com/t/X2noHoSz

On the View Booking page, there are 4 different records for the same order. For 13th Feb, there are 2 records and for 8th Feb, there is 2 record.

Also, when the order status is changed to Completed, the View booking page is showing the security codes for 13th Feb product and not for 8th Feb.

Here 'Send 1 ticket per quantity' setting is enabled for printable tickets.

**Comment by priyanka-tychesoftwares** [comment]
I am unable to replicate this issue now hence closing this one.
